# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

validation:
  planning_horizon: [2020]

# retrieving precomputed files from Google Drive and bypassing re-execution
retrieve_precomputed:
  cutouts: false # if true, US cutouts are retrieved from Google Drive, else it is retrieved using retrieve_databundle_light if enable is true
  osm_raw: true # if true, bypasses download_osm_data rule
  osm_clean: true # if true, bypasses clean_osm_data rule
  shapes: true # if true, bypasses build_shapes rule
  osm_network: true # if true, bypasses build_osm_network rule
  base_network: true # if true, bypasses base_network rule
  renewable_profiles: true # if true, bypasses build_renewable_profiles rule

custom_rules: ["workflow/custom.smk"]

costs:
  discountrate: [0.07] # from the `fill_values` section
  output_currency: "USD"
  year: 2030
  technology_data_version: v0.14.0
  country_specific_data: "US" # (optional) country-specific data are currently available only for "US"
  cost_scenario: "moderate" # only used if `country_specific_data: "US"`; can be "moderate", "advanced" or "conservative"
  cost_scenario_by_technology_group: # (optional): overwrites for some specific technology groups
    electricity: "moderate"
    H2_electrolysis: "moderate"
    dac: "moderate"
  financial_case: "market" # only used if `country_specific_data: "US"`; can be "market" or "r&d"
  discount rate:
    direct air capture: 0.10
    Fischer-Tropsch: 0.10
    Alkaline electrolyzer large size: 0.10
    Alkaline electrolyzer medium size: 0.10
    Alkaline electrolyzer small size: 0.10
    PEM electrolyzer small size: 0.10
    SOEC: 0.10
  lifetime:
    CCGT: 45
    OCGT: 45

cluster_options:
  aggregation_strategies:
    lines:
      tag_type: first
      tag_frequency: first
      underground: any
      under_construction: any

export:
  endogenous: false # If true, the export demand is endogenously determined by the model
  h2export: [0] # Yearly export demand in TWh. Only considered, if ["export"]["endogenous"] is set to false

# defining the aviation demand scenario
aviation_demand_scenario:
  country: US
  scenario: central # low, central or high

saf_mandate:
  ekerosene_split: true # separate e-kerosene as separate bus
  non_spatial_ekerosene: true # connects all e-kerosene buses with a single E-kerosene-main bus to model 0 cost of transport and store
  enable_mandate: false # enable SAF mandate
  saf_scenario: EU

demand_distribution:
  enable: true
  base_demand_year: 2023
  holes_area_threshold: 100
  nprocesses: 4
  plotting: true
  set_distribution_fees: true # true, false

demand_projection:
  planning_horizon: 2023
  scenario: "Medium"
  data_centers_load: true

state_policy: "on" # "off", "on" manage application of renewable/clean energy policies at State- or country-level

policy_config:
  hydrogen:
    temporal_matching: "hourly" # either "hourly", "monthly", "yearly", "no_temporal_matching"
    additionality: true
    temporal_matching_carriers: [csp, solar, onwind, offwind-ac, offwind-dc, ror, hydro, nuclear]
    h2_production_constraint: false

sector:
  co2_sequestration_potential: 250 # MtCO2/a sequestration potential for US
  co2_sequestration_cost: 8 # USD/tCO2 for sequestration of CO2
  demand_projection_reference_year: 2023
  ammonia:
    enable: false

  solar_rooftop: # adds distribution side customer rooftop PV (only work if electricity_distribution_grid: true)
    m2_per_person: 12

custom_industry:
  enable: true
  ethanol: true
  ammonia: true
  steel: true
  cement: true
  CCS_retrofit: [ethanol, ammonia, steel, cement] # [ethanol, ammonia, steel, cement]
  production_flexibility: []
  H2_DRI: false
  biogenic_co2: false # define output of ethanol from starch CC as biogenic CO2 to be used in Fischer-Tropsch
  grid_H2: true # mark output of electrolysis as grid H2 (which can be used in Fischer-Tropsch)
  other_electricity: true # add other electricity as a consumption
  dac_inputs:
    heat: false
    electricity: 1.4 # in MWh per ton CO2
  buffer_co2_stored: true # switch output to buffer co2 stored
  co2_storage_tanks: true # add CO2 storage tanks


custom_databundles:
  bundle_cutouts_USA:
    countries: [US]
    category: cutouts
    destination: "cutouts"
    urls:
      gdrive: https://drive.google.com/file/d/1Ao_kuHssRaP1qLV-IEG91Hu7E04-nBZg/view?usp=drive_link
    output: [cutouts/cutout-2013-era5.nc]
    disable_by_opt:
      build_cutout: [all]

  # precomputed raw osm data
  bundle_osm_raw_USA:
    countries: [US]
    category: resources_osm_raw
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/osm_raw.zip/content

  # precomputed clean osm data
  bundle_osm_clean_USA:
    countries: [US]
    category: resources_osm_clean
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/osm_clean.zip/content

  # precomputed shapes data
  bundle_shapes_USA:
    countries: [US]
    category: resources_shapes
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/shapes.zip/content

  # precomputed osm network data
  bundle_osm_network_USA:
    countries: [US]
    category: resources_osm_network
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/records/20747648/files/base_network_new_northamerica.zip/content

  # precomputed base.nc
  bundle_base_network_USA:
    countries: [US]
    category: resources_base_network
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/base_new_northamerica.nc.zip/content

  # precomputed renewable_profiles data
  bundle_renewable_profiles_USA:
    countries: [US]
    category: resources_renewable_profiles
    destination: "resources"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/renewable_profiles_voronoi_northamerica.zip/content

  # demand data used for demand redistribution
  bundle_demand_data_USA:
    countries: [US]
    category: data_demand_data
    destination: "data/custom/usa"
    urls:
      zenodo: https://zenodo.org/api/records/20747648/files/demand_data.zip/content
